
All:
	nasm -f elf64 print.asm 
	gcc -no-pie -Wall main.c print.o 
	./a.out

#All: Print Test
#
#Print:
#	@echo "Making all stuff:\n"
#	nasm -f elf64 print.asm -o print.o
#	ld print.o -o print
#
#Test:
#	@echo ""
#	@echo "Complite!"
#	@echo "OUT:\n"
#	./print